name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count authors in authors.txt
        run: |
          if [ -f authors.txt ]; then
            AUTHOR_COUNT=$(wc -l < authors.txt)
            echo "Number of authors: $AUTHOR_COUNT"
            if [ "$AUTHOR_COUNT" -eq 0 ]; then
              echo "Error: authors.txt is empty!"
              exit 1
            fi
          else
            echo "Error: authors.txt not found!"
            exit 1
          fi
